name: Lint
on:
- pull_request
- push

jobs:
  dockerfile:
    name: dockerfile
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - name: Run hadolint
       uses: hadolint/hadolint-action@v2.1.0

  markdownlint:
    name: markdown
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run markdownlint
      uses: actionshub/markdownlint@2.0.2

  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run shellcheck
      uses: ludeeus/action-shellcheck@1.1.0

  build:
    name: docker build test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master
    - name: Build Docker images
      uses: docker/build-push-action@v2
      id: build
      with:
        builder: ${{ steps.buildx.outputs.name }}
        load: true
        context: .
        tags: build-test
    - name: Anchore Container Vulnerability Scan
      uses: anchore/scan-action@v3
      id: scan
      with:
        image: build-test
        acs-report-enable: true
        fail-build: false
    - name: Upload Anchore Container Vulnerability Scan SARIF report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}
